version: '3'

services:
    app_vet:
        build: clinica_veterinaria

        mem_limit: 512m
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:mysql://clinica_vet:3306/clinica_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
            DB_USER_NAME: root

        container_name: app_vet
        restart: unless-stopped
        depends_on:
            clinica_vet:
                condition: service_healthy
        networks:
          - app-network


    clinica_vet:
        image: mysql:8.0.33
        container_name: clinica_vet
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mokimoki

            MYSQL_DATABASE: clinica_veterinaria
        restart: always
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 10s
            retries: 10
        networks:
            - app-network
networks:
    app-network:
        driver: bridge